/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DsmRouteImport } from "./routes/dsm";
import { Route as CrossReferenceExplorerRouteImport } from "./routes/cross-reference-explorer";
import { Route as IndexRouteImport } from "./routes/index";

const DsmRoute = DsmRouteImport.update({
  id: "/dsm",
  path: "/dsm",
  getParentRoute: () => rootRouteImport,
} as any);
const CrossReferenceExplorerRoute = CrossReferenceExplorerRouteImport.update({
  id: "/cross-reference-explorer",
  path: "/cross-reference-explorer",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/cross-reference-explorer": typeof CrossReferenceExplorerRoute;
  "/dsm": typeof DsmRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/cross-reference-explorer": typeof CrossReferenceExplorerRoute;
  "/dsm": typeof DsmRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/cross-reference-explorer": typeof CrossReferenceExplorerRoute;
  "/dsm": typeof DsmRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/cross-reference-explorer" | "/dsm";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/cross-reference-explorer" | "/dsm";
  id: "__root__" | "/" | "/cross-reference-explorer" | "/dsm";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CrossReferenceExplorerRoute: typeof CrossReferenceExplorerRoute;
  DsmRoute: typeof DsmRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dsm": {
      id: "/dsm";
      path: "/dsm";
      fullPath: "/dsm";
      preLoaderRoute: typeof DsmRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cross-reference-explorer": {
      id: "/cross-reference-explorer";
      path: "/cross-reference-explorer";
      fullPath: "/cross-reference-explorer";
      preLoaderRoute: typeof CrossReferenceExplorerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrossReferenceExplorerRoute: CrossReferenceExplorerRoute,
  DsmRoute: DsmRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
