/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as XrefRouteImport } from "./routes/xref";
import { Route as DependenciesRouteImport } from "./routes/dependencies";
import { Route as IndexRouteImport } from "./routes/index";

const XrefRoute = XrefRouteImport.update({
  id: "/xref",
  path: "/xref",
  getParentRoute: () => rootRouteImport,
} as any);
const DependenciesRoute = DependenciesRouteImport.update({
  id: "/dependencies",
  path: "/dependencies",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dependencies": typeof DependenciesRoute;
  "/xref": typeof XrefRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dependencies": typeof DependenciesRoute;
  "/xref": typeof XrefRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dependencies": typeof DependenciesRoute;
  "/xref": typeof XrefRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dependencies" | "/xref";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dependencies" | "/xref";
  id: "__root__" | "/" | "/dependencies" | "/xref";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DependenciesRoute: typeof DependenciesRoute;
  XrefRoute: typeof XrefRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/xref": {
      id: "/xref";
      path: "/xref";
      fullPath: "/xref";
      preLoaderRoute: typeof XrefRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dependencies": {
      id: "/dependencies";
      path: "/dependencies";
      fullPath: "/dependencies";
      preLoaderRoute: typeof DependenciesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DependenciesRoute: DependenciesRoute,
  XrefRoute: XrefRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
