jqassistant:
  store:
    uri: file:tools-example-db
  plugins:
    - group-id: com.buschmais.jqassistant.plugin 
      artifact-id: java
      version: 2.9.1
    - group-id: com.buschmais.jqassistant.plugin
      artifact-id: common
      version: 2.9.1
  analyze:
    concepts:
      - java-classpath:Resolve
      - java:TypeAssignableFrom
      - java:MethodOverrides
      - java:MemberInheritedFrom
      - java:VirtualInvokes
    groups:
      - hierograph:virtual-external
  scan:
    reset: true
