<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.slizaa</groupId>
    <artifactId>slizaa-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>slizaa Parent</name>
    <description>Parent for the slizaa project. </description>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <slizaa.version>1.0.0-SNAPSHOT</slizaa.version>
        <jqassistant.version>2.9.1</jqassistant.version>

        <!-- third-party versions -->
        <neo4j.version>5.26.26</neo4j.version>
        <neo4j-java-driver.version>5.28.13</neo4j-java-driver.version>
        <guava.version>33.2.1-jre</guava.version>
        <gson.version>2.11.0</gson.version>
        <slf4j.version>2.0.13</slf4j.version>
        <emf.version>2.12.0</emf.version>
        <classgraph.version>4.8.174</classgraph.version>
        <asm.version>9.7</asm.version>
        <commons-collections4.version>4.4</commons-collections4.version>
        <graphql-kickstart.version>11.1.0</graphql-kickstart.version>
        <spring-statemachine.version>4.0.0</spring-statemachine.version>
        <spring-boot.version>3.3.4</spring-boot.version>
        <maven-surefire-plugin.version>3.2.5</maven-surefire-plugin.version>

        <!-- test versions -->
        <junit.version>4.13.2</junit.version>
        <junit-vintage.version>5.11.2</junit-vintage.version>
        <mockito.version>5.11.0</mockito.version>
        <assertj.version>3.26.3</assertj.version>
        <awaitility.version>4.2.1</awaitility.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.buschmais.jqassistant</groupId>
                <artifactId>jqassistant-maven-plugin</artifactId>
                <version>${jqassistant.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>scan</goal>
                            <goal>analyze</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>

            <!-- ==================== -->
            <!-- Neo4j                -->
            <!-- ==================== -->
            <dependency>
                <groupId>org.neo4j</groupId>
                <artifactId>neo4j</artifactId>
                <version>${neo4j.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.neo4j</groupId>
                <artifactId>neo4j-procedure</artifactId>
                <version>${neo4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.neo4j.driver</groupId>
                <artifactId>neo4j-java-driver</artifactId>
                <version>${neo4j-java-driver.version}</version>
            </dependency>
            <dependency>
                <groupId>org.neo4j.test</groupId>
                <artifactId>neo4j-harness</artifactId>
                <version>${neo4j.version}</version>
            </dependency>

            <!-- ==================== -->
            <!-- Google               -->
            <!-- ==================== -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>

            <!-- ==================== -->
            <!-- Logging              -->
            <!-- ==================== -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-nop</artifactId>
                <version>${slf4j.version}</version>
            </dependency>

            <!-- ==================== -->
            <!-- Eclipse EMF          -->
            <!-- ==================== -->
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.common</artifactId>
                <version>${emf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.ecore</artifactId>
                <version>${emf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.edit</artifactId>
                <version>${emf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.ecore.xmi</artifactId>
                <version>${emf.version}</version>
            </dependency>

            <!-- ==================== -->
            <!-- Other third-party    -->
            <!-- ==================== -->
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>${asm.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.classgraph</groupId>
                <artifactId>classgraph</artifactId>
                <version>${classgraph.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons-collections4.version}</version>
            </dependency>
            <dependency>
                <groupId>com.graphql-java-kickstart</groupId>
                <artifactId>graphql-spring-boot-starter</artifactId>
                <version>${graphql-kickstart.version}</version>
            </dependency>
            <dependency>
                <groupId>com.graphql-java-kickstart</groupId>
                <artifactId>graphiql-spring-boot-starter</artifactId>
                <version>${graphql-kickstart.version}</version>
            </dependency>
            <dependency>
                <groupId>com.graphql-java-kickstart</groupId>
                <artifactId>graphql-spring-boot-starter-test</artifactId>
                <version>${graphql-kickstart.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.statemachine</groupId>
                <artifactId>spring-statemachine-core</artifactId>
                <version>${spring-statemachine.version}</version>
            </dependency>
            <dependency>
                <groupId>org.awaitility</groupId>
                <artifactId>awaitility</artifactId>
                <version>${awaitility.version}</version>
            </dependency>

            <!-- ==================== -->
            <!-- Test                 -->
            <!-- ==================== -->
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.vintage</groupId>
                <artifactId>junit-vintage-engine</artifactId>
                <version>${junit-vintage.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
            </dependency>

            <!-- ==================== -->
            <!-- slizaa modules       -->
            <!-- ==================== -->

            <!-- slizaa-core -->
            <dependency>
                <groupId>org.slizaa.core</groupId>
                <artifactId>org.slizaa.core.boltclient</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.core</groupId>
                <artifactId>org.slizaa.core.boltclient.testfwk</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.core</groupId>
                <artifactId>org.slizaa.core.mvnresolver.api</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.core</groupId>
                <artifactId>org.slizaa.core.mvnresolver.implementation</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.core</groupId>
                <artifactId>org.slizaa.core.mvnresolver.uber</artifactId>
                <version>${slizaa.version}</version>
            </dependency>

            <!-- slizaa-scanner-core -->
            <dependency>
                <groupId>org.slizaa.scanner</groupId>
                <artifactId>org.slizaa.scanner.spi-api</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.scanner</groupId>
                <artifactId>org.slizaa.scanner.contentdefinition</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.scanner</groupId>
                <artifactId>org.slizaa.scanner.cypherregistry</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.scanner</groupId>
                <artifactId>org.slizaa.scanner.testfwk</artifactId>
                <version>${slizaa.version}</version>
            </dependency>

            <!-- slizaa-hierarchicalgraph -->
            <dependency>
                <groupId>org.slizaa.hierarchicalgraph.core</groupId>
                <artifactId>org.slizaa.hierarchicalgraph.core.model</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.hierarchicalgraph.core</groupId>
                <artifactId>org.slizaa.hierarchicalgraph.core.algorithms</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.hierarchicalgraph.graphdb</groupId>
                <artifactId>org.slizaa.hierarchicalgraph.graphdb.model</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.hierarchicalgraph.graphdb</groupId>
                <artifactId>org.slizaa.hierarchicalgraph.graphdb.mapping.spi</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.hierarchicalgraph.graphdb</groupId>
                <artifactId>org.slizaa.hierarchicalgraph.graphdb.mapping.cypher</artifactId>
                <version>${slizaa.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slizaa.hierarchicalgraph.graphdb</groupId>
                <artifactId>org.slizaa.hierarchicalgraph.graphdb.mapping.service</artifactId>
                <version>${slizaa.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
