<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.hierograph</groupId>
        <artifactId>hierograph-parent</artifactId>
        <version>0.2.0-SNAPSHOT</version>
        <relativePath>../hierograph-parent/pom.xml</relativePath>
    </parent>

    <artifactId>hierograph-hierarchicalgraph</artifactId>
    <packaging>pom</packaging>

    <name>Hierograph Hierarchical Graph</name>
    <description>Pure Kotlin hierarchical graph implementation.</description>

    <modules>
        <module>io.hierograph.hierarchicalgraph.core.model</module>
        <module>io.hierograph.hierarchicalgraph.core.algorithms</module>
        <module>io.hierograph.hierarchicalgraph.graphdb.model</module>
        <module>io.hierograph.hierarchicalgraph.graphdb.mapping.spi</module>
        <module>io.hierograph.hierarchicalgraph.graphdb.mapping.service</module>
        <module>io.hierograph.hierarchicalgraph.serialization</module>
    </modules>
</project>
